import "./globals.css";

import { Jost } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";

import type { Metadata } from "next";

const jost = Jost({
	variable: "--font-jost",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type Props = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<Props>) {
	return (
		<html lang="en">
			<body className={`${jost.variable} antialiased transition-all duration-300`}>
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}
